# **Deep Learning Lab 1: Introduction to TensorFlow**

#TensorFlow 2.0 Introduction
In this notebook you will be given an interactive introduction to TensorFlow 2.0. We will walk through the following topics within the TensorFlow module:

- TensorFlow Install and Setup
- Representing Tensors
- Tensor Shape and Rank
- Types of Tensors


If you'd like to follow along without installing TensorFlow on your machine you can use **Google Collaboratory**. Collaboratory is a free Jupyter notebook environment that requires no setup and runs entirely in the cloud.

##Installing TensorFlow
To install TensorFlow on your local machine you can use pip.
```console
pip install tensorflow
```

![alt text](https://)If you have a CUDA enabled GPU you can install the GPU version of TensorFlow. You will also need to install some other software which can be found here: https://www.tensorflow.org/install/gpu 
```console
pip install tensorflow-gpu
```

## Importing TensorFlow
The first step here is going to be to select the correct version of TensorFlow from within collabratory!


In [ ]:
%tensorflow_version 2.x  # this line is not required unless you are in a notebook

`%tensorflow_version` only switches the major version: 1.x or 2.x.
You set: `2.x  # this line is not required unless you are in a notebook`. This will be interpreted as: `2.x`.


TensorFlow is already loaded. Please restart the runtime to change versions.


In [22]:
%tensorflow_version 2.x  # this line is not required unless you are in a notebook
import tensorflow as tf  # now import the tensorflow module
print(tf.version)  # make sure the version is 2.x
tf.test.gpu_device_name() 

`%tensorflow_version` only switches the major version: 1.x or 2.x.
You set: `2.x  # this line is not required unless you are in a notebook`. This will be interpreted as: `2.x`.


TensorFlow is already loaded. Please restart the runtime to change versions.
<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow/_api/v2/version/__init__.py'>


'/device:GPU:0'

**Note**: We will do all our work in Google Colab so giving %tensorflow_version 2.x is important

##Tensors 
"A tensor is a generalization of vectors and matrices to potentially higher dimensions. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes." (https://www.tensorflow.org/guide/tensor)

It should't surprise you that tensors are a fundemental apsect of TensorFlow. They are the main objects that are passed around and manipluated throughout the program. Each tensor represents a partialy defined computation that will eventually produce a value. TensorFlow programs work by building a graph of Tensor objects that details how tensors are related. Running different parts of the graph allow results to be generated.

Each tensor has a data type and a shape. 

**Data Types Include**: float32, int32, string and others.

**Shape**: Represents the dimension of data.

Just like vectors and matrices tensors can have operations applied to them like addition, subtraction, dot product, cross product etc.

In the next sections we will discuss some different properties of tensors. This is to make you more familiar with how tensorflow represnts data and how you can manipulate this data.


###Types of Tensors
Before we go to far, I will mention that there are diffent types of tensors. These are the most used and we will talk more in depth about each as they are used.
- Variable
- Constant
- Placeholder
- SparseTensor

With the exception of ```Variable``` all these tensors are immutable, meaning their value may not change during execution.

For now, it is enough to understand that we use the Variable tensor when we want to potentially change the value of our tensor.



###Creating Tensors
Below is an example of how to create some different tensors.

You simply define the value of the tensor and the datatype and you are good to go! It's worth mentioning that usually we deal with tensors of numeric data, it is quite rare to see string tensors.

For a full list of datatypes please refer to the following guide.

https://www.tensorflow.org/api_docs/python/tf/dtypes/DType?version=stable

In [23]:
string = tf.Variable("this is a string", tf.string) 
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

print(string)
print(number)
print(floating)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a string'>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=324>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.567>


###Rank/Degree of Tensors
Another word for rank is degree, these terms simply mean the number of dimensions involved in the tensor. What we created above is a *tensor of rank 0*, also known as a scalar. 

Now we'll create some tensors of higher degrees/ranks.

In [24]:
rank1_tensor = tf.Variable(["Test"], tf.string) 
rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"]], tf.string)

**To determine the rank** of a tensor we can call the following method.

In [25]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

The rank of a tensor is direclty related to the deepest level of nested lists. You can see in the first example ```["Test"]``` is a rank 1 tensor as the deepest level of nesting is 1. 
Where in the second example ```[["test", "ok"], ["test", "yes"]]``` is a rank 2 tensor as the deepest level of nesting is 2 (a list inside a list).

###Shape of Tensors
Now that we've talked about the rank of tensors it's time to talk about the shape. The shape of a tensor is simply the number of elements that exist in each dimension. TensorFlow will try to determine the shape of a tensor but sometimes it may be unknown.

To **get the shape** of a tensor we use the shape attribute.


In [26]:
rank2_tensor.shape

TensorShape([2, 2])

[2,2] means there are 2 lists and each list is having 2 elements, each list should have same no. of elements

###Changing Shape
The number of elements of a tensor is the product of the sizes of all its shapes. There are often many shapes that have the same number of elements, making it convient to be able to change the shape of a tensor.

The example below shows how to change the shape of a tensor.

In [27]:
tensor1 = tf.ones([1,2,3])  # tf.ones() creates a shape [1,2,3] tensor full of ones
tensor2 = tf.reshape(tensor1, [2,3,1])  # reshape existing data to shape [2,3,1]
tensor3 = tf.reshape(tensor2, [3, -1])  # -1 tells the tensor to calculate the size of the dimension in that place
                                        # this will reshape the tensor to [3,2]
                                                                             
# The numer of elements in the reshaped tensor MUST match the number in the original

Now let's have a look at our different tensors.

In [28]:
print(tensor1)
print(tensor2)
print(tensor3)
# Notice the changes in shape

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


###Slicing Tensors
You may be familiar with the term "slice" in python and its use on lists, tuples etc. Well the slice operator can be used on tensors to select specific axes or elements.

When we slice or select elements from a tensor, we can use comma seperated values inside the set of square brackets. Each subsequent value refrences a different dimension of the tensor.

Ex: ```tensor[dim1, dim2, dim3]```

I've included a few examples that will hopefully help illustrate how we can manipulate tensors with the slice operator.

In [29]:
# Creating a 2D tensor
matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]

tensor = tf.Variable(matrix, dtype=tf.int32) 
print(tf.rank(tensor))
print(tensor.shape)

tf.Tensor(2, shape=(), dtype=int32)
(4, 5)


In [30]:
# Now lets select some different rows and columns from our tensor

three = tensor[0,2]  # selects the 3rd element from the 1st row
print(three)  # -> 3

row1 = tensor[0]  # selects the first row
print(row1)

column1 = tensor[:, 0]  # selects the first column
print(column1)

row_2_and_4 = tensor[1::2]  # selects second and fourth row
print(row_2_and_4)

column_1_in_row_2_and_3 = tensor[1:3, 0] #selects column 1 in row 2 and 3
print(column_1_in_row_2_and_3)


tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)
tf.Tensor(
[[ 6  7  8  9 10]
 [16 17 18 19 20]], shape=(2, 5), dtype=int32)
tf.Tensor([ 6 11], shape=(2,), dtype=int32)


In [31]:
#Lets try to reshape a different tensor

t=tf.zeros([5,5,5,5])

t=tf.reshape(t,[625])

print(t)

t=tf.reshape(t,[125,-1]) # giving -1 will let Tensorflow calculate the dimesnsion 

print(t)

tf.Tensor(
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 

###Mathematical Operations on Tensors

Mathematical operations can be done on Tensor include addition, substraction, multiplication, division etc.

![Graphical View](https://drive.google.com/uc?export=view&id=1QrXd_jBV_RItKHDwcKOmlpO9PJSQZNkV)

We will also learn more about operations done normally on a Matrix like transpose

In [32]:
# Create the nodes in the graph, and initialize values
a = tf.constant(15)
b = tf.constant(61)

# Add them!
c1 = tf.add(a,b)
c2 = a + b # TensorFlow overrides the "+" operation so that it is able to act on Tensors
print(c1)
print(c2) # shape=() as it is a scalar value

tf.Tensor(76, shape=(), dtype=int32)
tf.Tensor(76, shape=(), dtype=int32)



Now you need to do something like this:
![alt text](https://drive.google.com/uc?export=view&id=1ZjSvfCZv1FYxJWK2-AlfjykEFnpuXIHp)

### Changing DataType of Tensor variables

Mathematical operations on tensors should be done on same data types as Python gives error incase it founds data mis-match.

So it is always better to convert into a particular datatype before operating on Tensors. For eg: for division operations it is preferable to cast the variable into Double data type (tf.float64)

In [33]:
import tensorflow as tf
a = tf.Variable(1)
b = tf.Variable(5.4,dtype=tf.float64)
print("a= ",a)
print("b= ",b)
print("ans =",tf.add(a,b))

a=  <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>
b=  <tf.Variable 'Variable:0' shape=() dtype=float64, numpy=5.4>


InvalidArgumentError: ignored

In [34]:
a = tf.dtypes.cast(tf.Variable(1),dtype=tf.float64)
b = tf.Variable(5.4,dtype=tf.float64)
print("a= ",a)
print("b= ",b)
print("ans =",tf.add(a,b))

a=  tf.Tensor(1.0, shape=(), dtype=float64)
b=  <tf.Variable 'Variable:0' shape=() dtype=float64, numpy=5.4>
ans = tf.Tensor(6.4, shape=(), dtype=float64)


### Matrix Creation and Operations

In [21]:
# initialization
import tensorflow as tf

a=tf.zeros([2,4]) # initialize as zeros
print(a)

a = tf.constant([[1, 2, 3], [4, 5, 6]]) # initialize by inserting constant values
print(a)

a=tf.random.normal([2,2],0,1,tf.float32) # intializes a matrix of shape [2,2] and values from a Normal Distribution
                                         # Normal Distribution of mean 0 and std_dev 1
print(a)

tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[-0.26904553 -0.85822237]
 [ 1.6771338  -1.0104401 ]], shape=(2, 2), dtype=float32)


For the Matrix operations we will use sample matrices with random normal distributed values

*   Transpose of a Matrix
*   Matrix Multiplication
*   Element Wise Multiplication

In [35]:
a=tf.random.normal([2,4],0,1,tf.float32) # intializes a matrix of shape [2,2] and values from a Normal Distribution
                                         # Normal Distribution of mean 0 and std_dev 1
print(a)

a=tf.transpose(a) # to find transpose of a matrix
print(a)

b= tf.random.normal([2,4],0,1,tf.float32) # initializing another matrix
print(b)

c=tf.matmul(a,b) #Matrix Multiplication: it should follow the rules

d=tf.multiply(a, tf.transpose(b)) #Element wise matrix multiplication: Dimension should be same

print(c)

print(d)

tf.Tensor(
[[-0.3494891   1.1032975   0.45863256 -0.15699323]
 [ 0.36473057 -0.3770235   1.597045    0.3323445 ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[-0.3494891   0.36473057]
 [ 1.1032975  -0.3770235 ]
 [ 0.45863256  1.597045  ]
 [-0.15699323  0.3323445 ]], shape=(4, 2), dtype=float32)
tf.Tensor(
[[ 1.5043411  -0.9866001  -0.40980533  0.7090512 ]
 [ 0.296673   -1.047608    2.4627318   1.1495425 ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[-0.4175451  -0.03728867  1.0414561   0.1714676 ]
 [ 1.5478832  -0.6935406  -1.3806449   0.3488899 ]
 [ 1.1637399  -2.125564    3.7451434   2.1610649 ]
 [-0.13757372 -0.19327722  0.882812    0.27072787]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[-0.5257508   0.10820571]
 [-1.0885134   0.39497283]
 [-0.18795006  3.9330935 ]
 [-0.11131623  0.3820441 ]], shape=(4, 2), dtype=float32)


#Sources
Most of the information is taken direclty from the TensorFlow website which can be found below.

https://www.tensorflow.org/guide/tensor